#!/bin/sh

##
#
# AWS configuration tester local credentials file and local config file
#
##
set -euf

# Helpers
out() { printf %s\\n "$*" ; }
err() { >&2 printf %s\\n "$*" ; }

credentials_file=${1:-$HOME/.aws/credentials}
config_file=${2:-$HOME/.aws/config}

for f in "$credentials_file" "$config_file"; do
    if [ -f "$f" ]; then
        out "Found file: $f"
    else
        err "Missing file: $f"
    fi
done

for s in aws_access_key_id aws_secret_access_key; do
    if grep -q "$s" "$credentials_file"; then
        out "Found credentials text: $s"
    else
        err "Missing credentials text: $s"
    fi
done

for s in region output; do
    if grep -q "$s" "$config_file"; then
        out "Found config text: $s"
    else
        err "Missing config text: $s"
    fi
done
