#!/bin/sh

##
# Delete AWS S3 bucket files that are older than a specified datetime.
#
# Syntax:
#
#     aws-s3-delete-objects-where-last-modified-is-less-than <bucket name> <cutoff datetime>
#
# Example:
#
#     bucket="mybucket"
#     cutoff="2020-01-01T01:01:01.000Z"
#     aws-s3-delete-objects-where-last-modified-is-less-than "$bucket" "$cutoff"
#
# Example for datetime delta of 30 days ago:
#
#     bucket="mybucket"
#     cutoff=$(date -u "+%Y-%m-%dT%H:%M:%S.%N+00:00" --date -30days)
#     aws-s3-delete-objects-where-last-modified-is-less-than "$bucket" "$cutoff"
##
set -euf

bucket="$1"
cutoff="$2"

aws s3api list-objects \
  --bucket "$bucket" \
  --no-paginate \
  --query 'Contents[?LastModified<`'$cutoff'`][].Key' | 
  jq -r '.[]' | 
  xargs -I{} aws s3api delete-object \
  --bucket "$bucket" \
  --key "{}"
